### ISSUE TITLE
Request Feature: Facebook Video

### ISSUE THREAD

**Issue by wilfredonoyola** [radiovisual/get-video-id#18]
Hi!

Currently, Facebook is launching many features about Video. Maybe this will be a big opportunity to add to support to Facebook.

Thanks,

**Comment by radiovisual** [comment]
@wilfredonoyola this is a good idea. Do you have a list of Facebook video url formats? 

PR is always welcome for this.

**Comment by radiovisual** [comment]
Closing this issue until either a PR is opened, or the demand is higher, or someone gets back to me with a list of known Facebook video URL patterns. I am not a big Facebook user, so I am not an expert here. PR is always welcome, but no movement on this issue since 2018, so I will consider this request a bit stale. Feel free to re-open.
