### ISSUE TITLE
Upgrading to 3.1.6 causes Uncaught TypeError: getVideoId is not a function

### ISSUE THREAD

**Issue by mikkopori** [radiovisual/get-video-id#48]
Upgrading caused this to start failing. Downgrading to 3.1.5 works fine.

```
const getVideoId = require('get-video-id');

export function parseVideoFromUrl(url) {
  const answer = getVideoId(url);

```
Also tried different other ways of importing and clearing the node_modules. They made no difference.

**Comment by radiovisual** [comment]
Thanks for reporting @mikkopori, I will take a look.

**Comment by stahlmanDesign** [comment]
I also have this error and think it might be because the module is no longer working on the front-end.

`TypeError: get_video_id__WEBPACK_IMPORTED_MODULE_7___default() is not a function`

When authoring npm modules that are both compatible in Node.js and in the browser, the build can't be TypeScript or the latest ES2020 etc., it has to be common js (last I knew)

Pinning to 3.1.5 for now

**Comment by jsg2021** [comment]
Webpack is picking the `browser` entry point. The browser entry point does not export anything, it simply defines a global variable.

**Comment by jsg2021** [comment]
The browser file could be converted to a UDM... and that could cover both commonjs and browser consumers... which would allow you to just have a main and module entry points... though, if you are using esm in the source, you may just want the module to point to src and only use a build step to generate the udm.

**Comment by mikkopori** [comment]
Thank you for the fix, works now!
