### ISSUE TITLE
https://www.youtube.com/watch/dQw4w9WgXcQ

### ISSUE THREAD

**Issue by easrng** [radiovisual/get-video-id#89]
**Describe the bug**  
URLs in the format https://www.youtube.com/watch/dQw4w9WgXcQ aren't recognized.

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Call `getVideoId` with the url string "https://www.youtube.com/watch/dQw4w9WgXcQ"
2. returns `{ id: undefined, service: 'youtube' }`

**Expected behavior**  
returns `{ id: 'dQw4w9WgXcQ', service: 'youtube' }`

**Environment**  
I can repro anywhere.

**Module version**  
The version of `get-video-id` where I am experiencing this problem is `v3.5.3`

**Comment by easrng** [comment]
I can make a PR for this

**Comment by radiovisual** [comment]
Nice catch! Thanks for reporting. This is such a popular format of the YouTube url that I literally thought I was being rick-rolled in this PR (because the URL you used in the reproduction steps) 😆 ...but then I saw that the module really isn't looking for this format and then I was like: **Hold my beer**, and then before I could even start working on the fix you had already created a PR. _Fun times all around!_

**Comment by radiovisual** [comment]
@easrng This feature has been added to the published version `3.6.2`. Enjoy!
